# Sabre Fighter Plane Simulator - Makefile for Mac OS X Tiger / PowerPC
# Build remotely: rsh 192.168.1.177 "cd /Volumes/pine/osx/sabreOSX && make -f Makefile.ppc"

APP_NAME    = Sabre
VERSION     = 0.2.4b
REV_DATE    = 11/21/99

SDL_PREFIX  = /Volumes/pine/osx/sdl12
SDLMIX_PREFIX = /Volumes/pine/osx/sdlmixer12

CXX         = g++
CC          = gcc

CXXFLAGS    = -Wall -O2 -Isrc \
              -DVERSION=\"$(VERSION)\" -DREV_DATE=\"$(REV_DATE)\"
CFLAGS      = -Wall -O2 -Isrc \
              -DVERSION=\"$(VERSION)\" -DREV_DATE=\"$(REV_DATE)\"

SDL_CFLAGS  = -I$(SDL_PREFIX)/include/SDL -I$(SDLMIX_PREFIX)/include/SDL
SDL_DEFINES = -DHAVE_LIBSDL=1
SDL_LIBS    = $(SDLMIX_PREFIX)/lib/libSDL_mixer.a \
              $(SDL_PREFIX)/lib/libSDLmain.a \
              $(SDL_PREFIX)/lib/libSDL.a \
              -framework Cocoa -framework Carbon -framework IOKit \
              -framework AudioUnit -framework AudioToolbox -framework CoreAudio \
              -framework OpenGL

CORE_CXX = \
  src/aaaunit.C src/aibase.C src/aiflite.C src/aigunner.C \
  src/aipilot.C src/aipilot2.C src/aipilot3.C src/aipilot4.C \
  src/aipilot5.C src/aipilot6.C src/bits.C src/clip.C \
  src/cockpit.C src/colormap.C src/colorspc.C src/convpoly.C \
  src/copoly.C src/cpoly.C src/dvector.C src/earth.C \
  src/flight.C src/fltlite.C src/fltmngr.C src/fltobj.C \
  src/fltzview.C src/font8x8.C src/fontdev.C src/game.C \
  src/globals.C src/grndunit.C src/group_3d.C src/hud.C \
  src/instrmnt.C src/key_map.C src/led2.C src/linux_joy.C \
  src/moveable.C src/mytimer.C src/obj_3d.C src/pen.C \
  src/pilobj.C src/pilot.C src/plltt.C src/port_3d.C \
  src/portkey.C src/ppm.C src/rendpoly.C src/rndrpoly.C \
  src/rndzpoly.C src/rotate.C src/sairfld.C src/sarray.C \
  src/sattkr.C src/sbfltmdl.C src/sbrkeys.C src/scnedit.C \
  src/sfltmdl.C src/sfrmtn.C src/simfile.C src/simfilex.C \
  src/siminput.C src/simmath.C src/smath.C src/smnvrst.C \
  src/sobject.C src/spilcaps.C src/splncaps.C src/srunway.C \
  src/sslewer.C src/stact.C src/starget.C src/swaypnt.C \
  src/sweapon.C src/target.C src/terrain.C src/transblt.C \
  src/traveler.C src/txtrmap.C src/unguided.C src/viewobj.C \
  src/vmath.C src/vtable2.C src/waypoint.C src/weapons.C \
  src/zview.C

CORE_C = src/dhlist.c src/spid.c src/stime.c \
         libzip/bits.c libzip/crc.c libzip/deflate.c \
         libzip/inflate.c libzip/trees.c libzip/unc.c

SDL_CXX = src/kbdhit.C src/main.C src/input.C src/vga_13.C src/simsnd.C
MENU_SRC = src/menu.C

BUILDDIR = build-ppc

CORE_CXX_O = $(patsubst %.C,$(BUILDDIR)/%.o,$(CORE_CXX))
CORE_C_O   = $(patsubst %.c,$(BUILDDIR)/%.o,$(CORE_C))
SDL_CXX_O  = $(patsubst %.C,$(BUILDDIR)/%.o,$(SDL_CXX))
MENU_O     = $(patsubst %.C,$(BUILDDIR)/%.o,$(MENU_SRC))

ALL_O  = $(CORE_CXX_O) $(CORE_C_O) $(SDL_CXX_O) $(MENU_O)
TARGET = src/sabre

.PHONY: all clean run

all: $(TARGET)

$(TARGET): $(ALL_O)
	$(CXX) -o $@ $^ $(SDL_LIBS) -lm

$(CORE_CXX_O): $(BUILDDIR)/%.o: %.C
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c -o $@ $<

$(CORE_C_O): $(BUILDDIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c -o $@ $<

$(SDL_CXX_O): $(BUILDDIR)/%.o: %.C
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(SDL_DEFINES) $(SDL_CFLAGS) -c -o $@ $<

$(MENU_O): $(BUILDDIR)/%.o: %.C
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(SDL_DEFINES) $(SDL_CFLAGS) -c -o $@ $<

run: $(TARGET)
	./$(TARGET)

clean:
	rm -rf $(BUILDDIR) $(TARGET)
